# Generated by Django 3.0.2 on 2020-03-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('addr_1', models.CharField(max_length=200)),
                ('addr_2', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='portfolio_app/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=250)),
                ('date_complete', models.DateField()),
                ('image', models.ImageField(upload_to='portfolio_app/images/')),
                ('image2', models.ImageField(blank=True, upload_to='portfolio_app/images/', verbose_name='Additional Image')),
                ('image3', models.ImageField(blank=True, upload_to='portfolio_app/images/', verbose_name='Additional Image')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
